version: '3.8'

services:
    web:
        env_file: .env
        build: .
        command: python /book_store_dir/Book_store/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY:${SECRET_KEY}
            - DEBUG:${DEBUG}
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
        volumes:
            - .:/book_store_dir
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        env_file: .env
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
 
    # adminer:
    #     image: adminer
    #     depends_on:
    #         - db
    #     restart: always
    #     ports:
    #         - 8080:8080

    # pgadmin:
    #     image: dpage/pgadmin4
    #     depends_on:
    #         - db
    #     ports:
    #         - 7070:80
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
    #         PGADMIN_DEFAULT_PASSWORD: admin
    #     restart: unless-stopped

volumes:
    postgres_data:
