version: '3.8'

services:
    web:
        env_file: .env
        build: .
        command: python /book_store_dir/Book_store/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY:${SECRET_KEY}
            - DEBUG:${DEBUG}
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
        volumes:
            - .:/book_store_dir
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        env_file: .env
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
