version: '3.8'

services:
    web:
        build: .
        command: python /book_store_dir/Book_store/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/book_store_dir
        ports:
            - 8000:8000